name: Update README.md with Wakatime Stats

on:
  schedule:
    - cron: '0 * * * *'  # updates every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Markscribe
      - uses: muesli/markscribe-action@master
        with:
          template: README.md
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
