name: Update README with Wakatime Stats

on:
  schedule:
    - cron: '0 * * * *'  # updates every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Markscribe
        uses: markscribe/markscribe-action@v1
        with:
          template: README.md
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
