# .github/workflows/markscribe.yml
name: Update README with Wakatime Stats

on:
  schedule:
    - cron:  '0 * * * *'    # every hour at minute 0
  workflow_dispatch:

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Markscribe
        uses: muesli/markscribe-action@v0.10.0
        with:
          input:  README.md
          output: README.md
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
